export { useUsersList } from './useUsersList'
export { useUserStats, invalidateStatsCache } from './useUserStats'
export { useUserPermissions } from './useUserPermissions'
export { useUserActions } from './useUserActions'
export { useDebouncedSearch } from './useDebouncedSearch'
export { usePendingOperations } from './usePendingOperations'
export { usePerformanceMonitoring, useRenderCount, useDebouncedEffect, useComponentMemory } from './usePerformanceMonitoring'
export { useAuditLogs } from './useAuditLogs'
export { useDashboardMetrics, useDashboardRecommendations, useDashboardAnalytics } from './useDashboardMetrics'
export { useFilterUsers, buildServerFilterQuery, type FilterOptions, type FilterConfig, type ServerFilterQuery } from './useFilterUsers'
export { useUnifiedUserService, type ServerFilterOptions as UnifiedServiceFilterOptions } from './useUnifiedUserService'
export { useServerSideFiltering, type ServerFilterOptions, type ServerFilterResponse } from './useServerSideFiltering'
export { useEntityForm, type FormMode, type ValidationRule, type FieldValidation, type EntityFormConfig } from './useEntityForm'
export { useUserManagementRealtime } from './useUserManagementRealtime'
export type { RealtimeOptions } from './useUserManagementRealtime'
export { useModalRealtime } from './useModalRealtime'
export type { EntityType } from './useModalRealtime'
export { useOptimisticUpdate, useBatchOptimisticUpdate } from './useOptimisticUpdate'
export type { OptimisticUpdateOptions } from './useOptimisticUpdate'

// Phase 7: Advanced Query Builder Hooks
export { useQueryBuilder } from './useQueryBuilder'
export { useFilterTemplates } from './useFilterTemplates'
