declare module 'lucide-react' {
    import { FC, SVGProps } from 'react'
    export interface LucideProps extends SVGProps<SVGSVGElement> {
        size?: string | number
        absoluteStrokeWidth?: boolean
    }
    export type Icon = FC<LucideProps>
    export const ArrowRight: Icon
    export const Check: Icon
    export const ChevronDown: Icon
    export const ChevronLeft: Icon
    export const ChevronRight: Icon
    export const ChevronUp: Icon
    export const Command: Icon
    export const CreditCard: Icon
    export const FileText: Icon
    export const HelpCircle: Icon
    export const Image: Icon
    export const Laptop: Icon
    export const Loader2: Icon
    export const Moon: Icon
    export const MoreVertical: Icon
    export const Pizza: Icon
    export const Plus: Icon
    export const Settings: Icon
    export const Settings2: Icon
    export const Sun: Icon
    export const Trash: Icon
    export const Twitter: Icon
    export const User: Icon
    export const X: Icon
    export const Search: Icon
    export const Bell: Icon
    export const Menu: Icon
    export const LogOut: Icon
    export const LayoutDashboard: Icon
    export const CheckSquare: Icon
    export const ShieldCheck: Icon
    export const DollarSign: Icon
    export const Activity: Icon
    export const TrendingUp: Icon
    export const TrendingDown: Icon
    export const Minus: Icon
    export const AlertCircle: Icon
    export const Clock: Icon
    export const CheckCircle: Icon
    export const Calendar: Icon
    export const Filter: Icon
    export const Users: Icon
    export const Upload: Icon
    export const Download: Icon
    export const RefreshCw: Icon
    export const Eye: Icon
    export const EyeOff: Icon
    export const Lock: Icon
    export const Unlock: Icon
    export const Mail: Icon
    export const Phone: Icon
    export const MapPin: Icon
    export const Globe: Icon
    export const Facebook: Icon
    export const Instagram: Icon
    export const Linkedin: Icon
    export const Github: Icon
    export const Youtube: Icon
    export const Slack: Icon
    export const MessageSquare: Icon
    export const Send: Icon
    export const Paperclip: Icon
    export const Link: Icon
    export const ExternalLink: Icon
    export const Copy: Icon
    export const Edit: Icon
    export const Edit2: Icon
    export const Edit3: Icon
    export const Archive: Icon
    export const Inbox: Icon
    export const Star: Icon
    export const Heart: Icon
    export const ThumbsUp: Icon
    export const ThumbsDown: Icon
    export const Smile: Icon
    export const Frown: Icon
    export const Meh: Icon
    export const AlertTriangle: Icon
    export const Info: Icon
    export const Home: Icon
    export const Briefcase: Icon
    export const Folder: Icon
    export const FolderPlus: Icon
    export const FolderMinus: Icon
    export const FolderOpen: Icon
    export const File: Icon
    export const FilePlus: Icon
    export const FileMinus: Icon
    export const FileDigit: Icon
    export const FileCode: Icon
    export const FileSpreadsheet: Icon
    export const FileAudio: Icon
    export const FileVideo: Icon
    export const FileImage: Icon
    export const FileArchive: Icon
    export const FileX: Icon
    export const FileCheck: Icon
    export const FileLock: Icon
    export const FileWarning: Icon
    export const FileQuestion: Icon
    export const FileSearch: Icon
    export const FileHeart: Icon
    export const FileOutput: Icon
    export const FileInput: Icon
    export const FileUp: Icon
    export const FileDown: Icon
    export const FileSymlink: Icon
    export const FileSymlink2: Icon
    export const FileVolume: Icon
    export const FileVolume1: Icon
    export const FileVolume2: Icon
    export const FileVolumeX: Icon
    export const FileMusic: Icon
    export const FileCamera: Icon
    export const FileTerminal: Icon
    export const FileCode2: Icon
    export const FileJson: Icon
    export const FileType: Icon
    export const FileType2: Icon
    export const FileDiff: Icon
    export const FileMinus2: Icon
    export const FilePlus2: Icon
    export const FileX2: Icon
    export const FileCheck2: Icon
    export const FileLock2: Icon
    export const FileWarning2: Icon
    export const FileQuestion2: Icon
    export const FileSearch2: Icon
    export const FileHeart2: Icon
    export const FileOutput2: Icon
    export const FileInput2: Icon
    export const FileUp2: Icon
    export const FileDown2: Icon
    export const FileSymlink3: Icon
    export const FileSymlink4: Icon
    export const FileVolume3: Icon
    export const FileVolume4: Icon
    export const FileVolume5: Icon
    export const FileVolumeX2: Icon
    export const FileMusic2: Icon
    export const FileCamera2: Icon
    export const Trash2: Icon
    export const Save: Icon
    export const ClipboardList: Icon
    export const Layout: Icon
    export const Award: Icon
    export const Target: Icon
    export const XCircle: Icon
    export const Building2: Icon
    export const Zap: Icon
    export const Timer: Icon
    export const Receipt: Icon
    export const Share2: Icon
    export const History: Icon
    export const ArrowLeft: Icon
    export const Building: Icon
    export const BarChart3: Icon
    export const Shield: Icon
    export const Tag: Icon
    export const Pencil: Icon
    export const List: Icon
    export const Lightbulb: Icon
    export const Code2: Icon
    export const Smartphone: Icon
    export const Workflow: Icon
    export const PieChart: Icon
    export const Gauge: Icon
    export const Maximize2: Icon
    export const Flag: Icon
    export const BookOpen: Icon
    export const Sparkles: Icon
    export const RotateCcw: Icon
    export const GitCompare: Icon
    export const MoreHorizontal: Icon
    export const ToggleRight: Icon
    export const Play: Icon
    export const RotateCw: Icon
    export const UserPlus: Icon
    export const UserCheck: Icon
    export const LogIn: Icon
    export const Monitor: Icon
    export const Bookmark: Icon
    export const Pause: Icon
    export const ZoomIn: Icon
    export const ZoomOut: Icon
    export const Calculator: Icon
    export const MousePointer: Icon
    export const Circle: Icon
    export const DownloadCloud: Icon
    export const StarOff: Icon
    export const MessageCircle: Icon
    export const Book: Icon
    export const Palette: Icon
    export const Wallet: Icon
    export const ShoppingCart: Icon
    export const Package2: Icon
    export const Bug: Icon
    export const Wifi: Icon
    export const WifiOff: Icon
    export const Server: Icon
    export const Database: Icon
    export const Plug: Icon
    export const ListChecks: Icon
    export const UserCog: Icon
    export const GripVertical: Icon
    export const Code: Icon
    export type LucideIcon = Icon
    export const Sliders: Icon
    export const PlusCircle: Icon
    export const MinusCircle: Icon
    export const ZapOff: Icon
    export const Slash: Icon
    export const Minimize2: Icon
    export const Grid3x3: Icon
    export const SlidersHorizontal: Icon
    export const Quote: Icon
    export const Camera: Icon
    export const ArrowDown: Icon
    export const ArrowUp: Icon
    export const Ban: Icon
    export const Rocket: Icon
    export const LineChart: Icon
    export const Flame: Icon
    export const PlayCircle: Icon
    export const Ticket: Icon
    export const CheckCheck: Icon
    export const Repeat: Icon
    export const AtSign: Icon
    export const Bold: Icon
    export const Italic: Icon
    export const ShieldAlert: Icon
    export const UploadCloud: Icon
    export const Clipboard: Icon
    export const Reply: Icon
    export const InfoIcon: Icon
    export const UserCircle: Icon
    export const CheckIcon: Icon
    export const CircleIcon: Icon
    export const Cog: Icon
    export const PlugZap: Icon
    export const ServerCog: Icon
    export const CheckCircle2: Icon
    export const ChevronUpIcon: Icon
    export const CalendarDays: Icon
    export const Loader: Icon
    export const XIcon: Icon
    export const ChevronRightIcon: Icon
    export const ChevronDownIcon: Icon
    export const ChevronsRight: Icon
    export const Link2: Icon
    export const FileEdit: Icon
    export const SmilePlus: Icon
    export const CalendarIcon: Icon
    export const ChevronsLeft: Icon
    export const UserX: Icon
    // Add other icons as needed
}
